# Generated by Django 5.1.2 on 2025-10-25 08:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Task title", max_length=200)),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the task"),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Optional file attachment",
                        null=True,
                        upload_to="task_attachments/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "txt",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "zip",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when task was created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when task was last modified"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created this task",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="tasks_task_user_id_d01da7_idx",
                    ),
                    models.Index(fields=["title"], name="tasks_task_title_6b13c2_idx"),
                ],
            },
        ),
    ]
