# Generated by Django 5.1.2 on 2025-10-26 06:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Optional file attachment for the task.",
                null=True,
                upload_to="task_attachments/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "doc",
                            "docx",
                            "txt",
                            "jpg",
                            "jpeg",
                            "png",
                            "zip",
                        ]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the task was created."
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(help_text="Detailed description of the task."),
        ),
        migrations.AlterField(
            model_name="task",
            name="modified_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the task was last modified."
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(help_text="Title of the task.", max_length=200),
        ),
        migrations.AlterField(
            model_name="task",
            name="user",
            field=models.ForeignKey(
                help_text="User who created this task.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
